DATABASE_URL = "postgres://boat_user:pass12@127.0.0.1:5432/boat_maintenance"
SLACK_URL = "https://hooks.slack.com/services/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"
SLEEP_SECONDS = 15
RESEND_MINUTES = 60
MONITOR_URLS = ["https://www.yachtlogger.com/heartbeat"]
DB_QUERIES = [
    ["user count", "select count(*) as count from users"]]
